"""with roles

Revision ID: 0884800e0264
Revises: 1566520c31e2
Create Date: 2020-03-19 09:05:46.521947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0884800e0264'
down_revision = '1566520c31e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('survey_data')
    op.add_column('SurveyData', sa.Column('role04', sa.Text(), nullable=True))
    op.add_column('SurveyData', sa.Column('role05', sa.Text(), nullable=True))
    op.add_column('SurveyData', sa.Column('role06', sa.Text(), nullable=True))
    op.add_column('SurveyData', sa.Column('role07', sa.Text(), nullable=True))
    op.add_column('SurveyData', sa.Column('role08', sa.Text(), nullable=True))
    op.add_column('SurveyData', sa.Column('role09', sa.Text(), nullable=True))
    op.add_column('SurveyData', sa.Column('role10', sa.Text(), nullable=True))
    op.add_column('SurveyData', sa.Column('role11', sa.Text(), nullable=True))
    op.add_column('SurveyData', sa.Column('role12', sa.Text(), nullable=True))
    op.add_column('SurveyData', sa.Column('role13', sa.Text(), nullable=True))
    op.add_column('SurveyData', sa.Column('role14', sa.Text(), nullable=True))
    op.add_column('SurveyData', sa.Column('role15', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('SurveyData', 'role15')
    op.drop_column('SurveyData', 'role14')
    op.drop_column('SurveyData', 'role13')
    op.drop_column('SurveyData', 'role12')
    op.drop_column('SurveyData', 'role11')
    op.drop_column('SurveyData', 'role10')
    op.drop_column('SurveyData', 'role09')
    op.drop_column('SurveyData', 'role08')
    op.drop_column('SurveyData', 'role07')
    op.drop_column('SurveyData', 'role06')
    op.drop_column('SurveyData', 'role05')
    op.drop_column('SurveyData', 'role04')
    op.create_table('survey_data',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('role01', sa.TEXT(), nullable=True),
    sa.Column('construct1neg', sa.TEXT(), nullable=True),
    sa.Column('construct1pos', sa.TEXT(), nullable=True),
    sa.Column('oddgoose01', sa.INTEGER(), nullable=True),
    sa.Column('rating_p1_const1', sa.INTEGER(), nullable=True),
    sa.Column('role02', sa.TEXT(), nullable=True),
    sa.Column('role03', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
