"""add 4 ratings

Revision ID: 42871097d111
Revises: 69574096eb97
Create Date: 2020-03-19 11:43:23.351453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42871097d111'
down_revision = '69574096eb97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('SurveyData', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating_p1_const1', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rating_p1_const2', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rating_p2_const1', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rating_p2_const2', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('SurveyData', schema=None) as batch_op:
        batch_op.drop_column('rating_p2_const2')
        batch_op.drop_column('rating_p2_const1')
        batch_op.drop_column('rating_p1_const2')
        batch_op.drop_column('rating_p1_const1')

    # ### end Alembic commands ###
