"""add timestamp

Revision ID: 552d2d8a70f3
Revises: dbb8c89266d8
Create Date: 2020-03-19 10:12:19.586610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '552d2d8a70f3'
down_revision = 'dbb8c89266d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('SurveyData', sa.Column('timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('SurveyData', 'timestamp')
    # ### end Alembic commands ###
