"""looped rating

Revision ID: 6650dbe6356b
Revises: 42871097d111
Create Date: 2020-03-19 21:07:35.141581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6650dbe6356b'
down_revision = '42871097d111'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('SurveyData', schema=None) as batch_op:
        batch_op.drop_column('rating_p2_const2')
        batch_op.drop_column('rating_p1_const1')
        batch_op.drop_column('rating_p2_const1')
        batch_op.drop_column('rating_p1_const2')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('SurveyData', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating_p1_const2', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('rating_p2_const1', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('rating_p1_const1', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('rating_p2_const2', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
