"""update with constructs for P1

Revision ID: 9db176a04d80
Revises: 6650dbe6356b
Create Date: 2020-03-31 11:38:17.073456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9db176a04d80'
down_revision = '6650dbe6356b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('SurveyData', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating_p1_const1', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rating_p1_const10', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rating_p1_const11', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rating_p1_const12', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rating_p1_const13', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rating_p1_const14', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rating_p1_const15', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rating_p1_const2', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rating_p1_const3', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rating_p1_const4', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rating_p1_const5', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rating_p1_const6', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rating_p1_const7', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rating_p1_const8', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rating_p1_const9', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('SurveyData', schema=None) as batch_op:
        batch_op.drop_column('rating_p1_const9')
        batch_op.drop_column('rating_p1_const8')
        batch_op.drop_column('rating_p1_const7')
        batch_op.drop_column('rating_p1_const6')
        batch_op.drop_column('rating_p1_const5')
        batch_op.drop_column('rating_p1_const4')
        batch_op.drop_column('rating_p1_const3')
        batch_op.drop_column('rating_p1_const2')
        batch_op.drop_column('rating_p1_const15')
        batch_op.drop_column('rating_p1_const14')
        batch_op.drop_column('rating_p1_const13')
        batch_op.drop_column('rating_p1_const12')
        batch_op.drop_column('rating_p1_const11')
        batch_op.drop_column('rating_p1_const10')
        batch_op.drop_column('rating_p1_const1')

    # ### end Alembic commands ###
