"""adding one set of role comp construct rate

Revision ID: 1566520c31e2
Revises: 2a0985bfb178
Create Date: 2020-02-13 10:52:23.282487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1566520c31e2'
down_revision = '2a0985bfb178'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('survey_data', sa.Column('construct1neg', sa.Text(), nullable=True))
    op.add_column('survey_data', sa.Column('construct1pos', sa.Text(), nullable=True))
    op.add_column('survey_data', sa.Column('oddgoose01', sa.Integer(), nullable=True))
    op.add_column('survey_data', sa.Column('rating_p1_const1', sa.Integer(), nullable=True))
    op.add_column('survey_data', sa.Column('role02', sa.Text(), nullable=True))
    op.add_column('survey_data', sa.Column('role03', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('survey_data', 'role03')
    op.drop_column('survey_data', 'role02')
    op.drop_column('survey_data', 'rating_p1_const1')
    op.drop_column('survey_data', 'oddgoose01')
    op.drop_column('survey_data', 'construct1pos')
    op.drop_column('survey_data', 'construct1neg')
    # ### end Alembic commands ###
