"""ratings v.1

Revision ID: 433edb91b9e2
Revises: 552d2d8a70f3
Create Date: 2020-03-19 11:12:19.509322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '433edb91b9e2'
down_revision = '552d2d8a70f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('SurveyData', sa.Column('val', sa.Text(), nullable=True))
    op.drop_column('SurveyData', 'rating_p1_const1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('SurveyData', sa.Column('rating_p1_const1', sa.INTEGER(), nullable=True))
    op.drop_column('SurveyData', 'val')
    # ### end Alembic commands ###
