"""empty message

Revision ID: 47d853491d06
Revises: 433edb91b9e2
Create Date: 2020-03-19 11:31:37.666585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47d853491d06'
down_revision = '433edb91b9e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('SurveyData', sa.Column('rating_p1_const2', sa.Integer(), nullable=True))
    op.add_column('SurveyData', sa.Column('rating_p2_const1', sa.Integer(), nullable=True))
    op.add_column('SurveyData', sa.Column('rating_p2_const2', sa.Integer(), nullable=True))
    op.drop_column('SurveyData', 'val')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('SurveyData', sa.Column('val', sa.TEXT(), nullable=True))
    op.drop_column('SurveyData', 'rating_p2_const2')
    op.drop_column('SurveyData', 'rating_p2_const1')
    op.drop_column('SurveyData', 'rating_p1_const2')
    # ### end Alembic commands ###
