"""adding self ratings

Revision ID: ea13cf9c605c
Revises: 4d15213edd8f
Create Date: 2020-04-26 20:37:03.121988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea13cf9c605c'
down_revision = '4d15213edd8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('SurveyData', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating_p16_const1', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rating_p16_const10', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rating_p16_const11', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rating_p16_const12', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rating_p16_const13', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rating_p16_const14', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rating_p16_const15', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rating_p16_const2', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rating_p16_const3', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rating_p16_const4', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rating_p16_const5', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rating_p16_const6', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rating_p16_const7', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rating_p16_const8', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rating_p16_const9', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('SurveyData', schema=None) as batch_op:
        batch_op.drop_column('rating_p16_const9')
        batch_op.drop_column('rating_p16_const8')
        batch_op.drop_column('rating_p16_const7')
        batch_op.drop_column('rating_p16_const6')
        batch_op.drop_column('rating_p16_const5')
        batch_op.drop_column('rating_p16_const4')
        batch_op.drop_column('rating_p16_const3')
        batch_op.drop_column('rating_p16_const2')
        batch_op.drop_column('rating_p16_const15')
        batch_op.drop_column('rating_p16_const14')
        batch_op.drop_column('rating_p16_const13')
        batch_op.drop_column('rating_p16_const12')
        batch_op.drop_column('rating_p16_const11')
        batch_op.drop_column('rating_p16_const10')
        batch_op.drop_column('rating_p16_const1')

    # ### end Alembic commands ###
